import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { HeaderNav } from "@/components/HeaderNav";
import { UserSyncProvider } from "@/components/UserSyncProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          <UserSyncProvider>
            <LanguageProvider>
              <HeaderNav />
              {children}
            </LanguageProvider>
          </UserSyncProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
